### ISSUE TITLE
 The slides of Hydiff on ICSE2020

### ISSUE THREAD

**Issue by blu3sh0rk** [yannicnoller/hydiff#1]
Hello!

    whrere and How can I get the slides of Hydiff on ICSE2020?

**Comment by yannicnoller** [comment]
Hi @LucasLeeNDS!

You can find them on my homepage: [https://yannicnoller.github.io/publications/](https://yannicnoller.github.io/publications/). 
Here is a direct link to the [PDF](https://yannicnoller.github.io/slides/icse2020_noller_hydiff_slides.pdf).

**Comment by blu3sh0rk** [comment]
OK，thank you~



发自我的iPhone


------------------ Original ------------------
From: Yannic Noller ***@***.***&gt;
Date: Tue,Jan 4,2022 9:02 AM
To: yannicnoller/hydiff ***@***.***&gt;
Cc: LucasLeeNDS ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [yannicnoller/hydiff]  The slides of Hydiff on ICSE2020 (Issue #1)





 
Hi @LucasLeeNDS!
 
You can find them on my homepage: https://yannicnoller.github.io/publications/.
 Here is a direct link to the PDF.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
